### PR TITLE
fix: skip write_only=True fields

### PR DESCRIPTION
**Pull request by JasperSui**
This should solve issue #52.

### CODE REVIEW

**Comment by JasperSui** [comment]
@GeeWee Please review this PR if you are available, thanks.

**Comment by GeeWee** [comment]
Yeah this looks good to me!

**Comment by GeeWee** [comment]
I expect to release to PyPi sometime later this week hopefully.

**Comment by GeeWee** [comment]
Released in 0.2.12!

**Comment by JasperSui** [comment]
Awesome, thanks!

**Pull request merged**
