### PR TITLE
expose exclude_fields and extra_fields API in ViewSetMixin

### PR DESCRIPTION
**Pull request by siteshen**

### CODE REVIEW

**Comment by GeeWee** [comment]
Nice - would you mind adding a test or two and update the documentation as well? If the docs are too much effort I can do that.

**Comment by siteshen** [comment]
> Nice - would you mind adding a test or two and update the documentation as well? If the docs are too much effort I can do that.

I'm not familiar with the testing framework, and adding test cases or proper documentation was too difficult for me.

**Comment by GeeWee** [comment]
Let me see if I can find some time to do it within the next week or so then :)

**Comment by GeeWee** [comment]
Found some time! Merged it in via #43 - thanks for your contribution.

**Pull request closed without merging**
