### PR TITLE
fix: don't auto prefetch properties

### PR DESCRIPTION
**Pull request by hemache**
Avoid prefetching fields (using `select_related`) where `Serializer.source` param points to a `property` and not an actual field or field descriptor
Error
### Example

```python
class User(Model, ...):
  @property
   def primary_phone_number(self):
     return self.phone_numbers.first()


class UserSerializer(...):
  primary_phone_number = PhoneNumberSerializer(read_only=True)


class UserViewSet(AutoPrefetchViewSetMixin, ...):
  pass
```

##### Results

```
FieldError at /api/users/
Invalid field name(s) given in select_related: 'primary_phone_number'. Choices are: profile
```

### CODE REVIEW

**Comment by GeeWee** [comment]
I'd like to merge this in - can you update the PR description to give a little more information so that the git changelog will reflect exactly what the change does?

**Comment by hemache** [comment]
@GeeWee done :pray:

**Comment by GeeWee** [comment]
Turns out that a lot of the previous tests fail (check the CI) - I have a feeling that your change probably breaks a bunch of stuff that you didn't mean for it to.
I'll need you to either change the code, or demonstrate why the tests are broken/fix them to merge this in :)

**Comment by hemache** [comment]
fixed failing tests, could you please recheck now?

**Comment by hemache** [comment]
Hey @GeeWee, any updates?

**Comment by GeeWee** [comment]
Yeah sorry, I expect to merge this in and publish a new version during the weekend :)

**Comment by GeeWee** [comment]
0.1.10 released with this PR. Thanks for the patience! :champagne:

**Pull request merged**
